# Use an official Python runtime as a parent image
FROM rust:slim-bookworm

# Set the working directory in the container
WORKDIR /usr/src/app

# Clone the latest Opteryx repository
RUN apt-get update && apt-get install -y --no-install-suggests --no-install-recommends python3 python3-venv gcc git 

RUN python3 -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"


RUN git clone https://github.com/mabel-dev/opteryx.git
RUN git clone https://github.com/mabel-dev/orso.git

# Install any needed packages specified in requirements.txt
# Assuming Opteryx has a requirements.txt file for its dependencies
RUN python3 -m pip install --no-cache-dir --upgrade numpy cython

RUN python3 -m pip install --no-cache-dir -r orso/requirements.txt
RUN python3 orso/setup.py build_ext --inplace


RUN python3 -m pip install --no-cache-dir -r opteryx/requirements.txt
RUN python3 opteryx/setup.py build_ext --inplace

# Clone the test suite repository and copy the test script
RUN git clone https://github.com/mabel-dev/wrenchy-bench.git && \
    cp wrenchy-bench/bench/performance.py ./


# Run the test script when the container launches
CMD ["python3", "./performance.py"]
